apiVersion: 1

datasources:
  - name: fleet-mariadb
    uid: fleet-mariadb
    type: mysql
    access: proxy
    url: mariadb:3306
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: fleet
    isDefault: true
    editable: false
