apiVersion: 1

datasources:
  - name: wired-mariadb
    uid: wired-mariadb
    type: mysql
    access: proxy
    url: mariadb:3306
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: wired
    isDefault: true
    editable: false
